include("../src/GeneExpressionProgramming.jl")

using .GeneExpressionProgramming

include("Entity_test.jl")
include("threading_test.jl")
include("Spb_core_test.jl")
include("sbp_gating_test.jl")
include("sbp_repair_test.jl")
include("sbp_homogeneity_test.jl")
include("gene_averaging_test.jl")
include("non_dom_sort_test.jl")
include("regression_wrapper_test.jl")
include("tensor_ops_test.jl")
include("reproducibility_test.jl")
include("linear_scaling_test.jl")
include("monomorphic_eval_test.jl")
include("tensor_dimensions_test.jl")
include("surrogate_test.jl")
include("simplex_test.jl")
